"""Add soft delete support for hotels

Revision ID: 3c7692f39289
Revises: a986d1c11acc
Create Date: 2026-08-01 12:09:34.581858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7692f39289'
down_revision = 'a986d1c11acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_removed', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('date_removed')

    # ### end Alembic commands ###
